// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /**
    * @ngdoc overview
    * @name pomodoroTimer
    * @description
    * # pomodoroTimer
   #
    * Main module of the application.
   */
  angular.module('pomodoroTimer', []).controller('PomodoroController', [
    '$scope', '$rootScope', '$interval', function($scope, $rootScope, $interval) {
      var AUDIOS, COUNTDOWN_RESOLUTION_MS, CYCLE_BREAK, CYCLE_WORK, NOTIFICATION_AUTO_CLOSE_DURATION_MS, Notification, TIME_BREAK_MS, TIME_WORK_MS, calcRemaingTime, currentCycle, dtDist, dtStart, init, isRunning, playAudio, remaingTimeMs, setTargetTime, showNotification, stopPromise, tick, toggleCycle, updateBackground, updateTimerDisplay;
      TIME_WORK_MS = 5000;
      TIME_BREAK_MS = 5000;
      CYCLE_WORK = 'work';
      CYCLE_BREAK = 'break';
      COUNTDOWN_RESOLUTION_MS = 100;
      NOTIFICATION_AUTO_CLOSE_DURATION_MS = 15000;
      AUDIOS = {
        START: new Audio('assets/audio/start.m4a'),
        PAUSE: new Audio('assets/audio/pause.m4a'),
        WORK: new Audio('assets/audio/work.m4a'),
        BREAK: new Audio('assets/audio/break.m4a')
      };
      stopPromise = void 0;
      currentCycle = void 0;
      dtStart = dtDist = void 0;
      remaingTimeMs = 0;
      isRunning = false;
      Notification = window.Notification || window.mozNotification || window.webkitNotification;
      if (Notification && Notification.permission !== 'granted') {
        Notification.requestPermission(function(permission) {});
      }
      showNotification = function(msg) {
        var instance;
        if (Notification && Notification.permission === 'granted') {
          instance = new Notification('Time Expired', {
            body: msg,
            icon: 'assets/img/alarm.png'
          });
          instance.onshow = function() {
            return setTimeout(function() {
              return instance.close();
            }, NOTIFICATION_AUTO_CLOSE_DURATION_MS);
          };
        }
        return false;
      };
      playAudio = function(audioType) {
        return audioType.play();
      };
      updateBackground = function(cycle) {
        return $scope.cycleColor = "cycle-" + cycle;
      };
      updateTimerDisplay = function(ms, cycle) {
        var min, sec, timerDisplay;
        min = Math.floor(ms / 1000 / 60);
        sec = Math.floor(ms / 1000 % 60);
        timerDisplay = ms < 0 ? '00:00' : timerDisplay = ('00' + min).substr(-2) + ':' + ('00' + sec).substr(-2);
        $scope.indicator = {
          cycle: cycle,
          time: timerDisplay
        };
        $rootScope.title = cycle + " " + timerDisplay;
        return timerDisplay;
      };
      toggleCycle = function() {
        currentCycle = currentCycle === CYCLE_WORK ? CYCLE_BREAK : CYCLE_WORK;
        switch (currentCycle) {
          case CYCLE_WORK:
            showNotification('Get back to work.');
            playAudio(AUDIOS.WORK);
            setTargetTime(TIME_WORK_MS);
            break;
          default:
            showNotification('Have a break.');
            playAudio(AUDIOS.BREAK);
            setTargetTime(TIME_BREAK_MS);
        }
        updateBackground(currentCycle);
        return tick();
      };
      setTargetTime = function(intervalMs) {
        dtStart = new Date();
        return dtDist = new Date(dtStart.getTime() + intervalMs);
      };
      calcRemaingTime = function() {
        return dtDist.getTime() - Date.now();
      };
      tick = function() {
        remaingTimeMs = calcRemaingTime();
        return updateTimerDisplay(remaingTimeMs, currentCycle);
      };
      init = function() {
        isRunning = false;
        currentCycle = CYCLE_WORK;
        updateBackground('stop');
        remaingTimeMs = TIME_WORK_MS;
        return updateTimerDisplay(remaingTimeMs, currentCycle);
      };
      $scope.runPomodoro = function() {
        updateBackground(currentCycle);
        if (angular.isDefined(stopPromise)) {
          return;
        }
        if (!isRunning) {
          setTargetTime(TIME_WORK_MS);
          isRunning = true;
        }
        playAudio(AUDIOS.START);
        return stopPromise = $interval(function() {
          if (remaingTimeMs > 0) {
            return tick();
          } else {
            return toggleCycle();
          }
        }, COUNTDOWN_RESOLUTION_MS);
      };
      $scope.pausePomodoro = function() {
        if (angular.isDefined(stopPromise)) {
          $interval.cancel(stopPromise);
          stopPromise = void 0;
          playAudio(AUDIOS.PAUSE);
          return updateBackground('stop');
        }
      };
      $scope.resetPomodoro = function() {
        $scope.pausePomodoro();
        return init();
      };
      $scope.$on('$destroy', function() {
        return $scope.pausePomodoro();
      });
      return $scope.$watch('$viewContentLoaded', function() {
        return init();
      });
    }
  ]).directive('ptIndicator', function() {
    return {
      restrict: 'E',
      scope: {
        indicator: '='
      },
      templateUrl: 'app/indicator.tpl.html'
    };
  });

}).call(this);
